image:
  name: clevercloud/clever-tools:latest
  entrypoint: [""]

#-------------------------------
# Deploy
#-------------------------------
deploy to production:
  stage: deploy
  script: clever link ${APP_ID}; clever deploy
  environment: production